### Question 1:

### Answer:

B. RAINBOW

### Question 2:
Write a program that prints “LETS UPGRADE”. (Please note that you have to print in ALL CAPS
as given)

In [1]:
string = 'LETS UPGRADE'

print(string)

LETS UPGRADE


### Question 3:

Write a program that takes cost price and selling price as input and
displays whether the transaction is a Profit or a Loss or Neither.

In [7]:
cost_price = int(input())
sell_price = int(input())

if cost_price > sell_price:
    print('Loss')

elif cost_price < sell_price:
    print('Profit')
    
else:
    print('Neither')

20
30
Profit


### Question 4:
Write a program that takes an amount in Euros as input. You need to find its equivalent in
Rupees and display it. Assume 1 Euro equals Rs. 80.

In [8]:
amt_in_euro = float(input())
amt_in_inr = amt_in_euro * 80
print(amt_in_inr)

20
1600.0


### Question 5:
Create an empty list. Accept 10 numbers from the user and append to it the list if it is an even
number.

In [16]:
ls = []

for i in range(10):
    i = int(input())
    if i%2 == 0: # checking th even num conditon
        ls.append(i) # appending i 
    
print(ls)




12
34
145
78
09
67
56
45
87
89
[12, 34, 78, 56]


### Question 6:
Create a notebook on LIST COMPREHENSION. This exercise is to put you in a
Self-learning mode

In [21]:
# even number from 0 to 50

even = [ x for x in range(50) if x % 2 == 0 ]

print(list(even))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


In [24]:
# square of number from 1 to 11

square = [ i**2 for i in range(1, 11)]

print(list(square))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [26]:
# number divisible by 2 and 3

nums = [ i for i in range(100) if i % 2 == 0 and i % 3 == 0 ]

print(nums)

[0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60, 66, 72, 78, 84, 90, 96]


In [28]:
# printing even or odd

list = [ 'EVEN' if i % 2 == 0 else 'ODD' for i in range(10)]

print(list)

['EVEN', 'ODD', 'EVEN', 'ODD', 'EVEN', 'ODD', 'EVEN', 'ODD', 'EVEN', 'ODD']


### Question 7:
You have seen in the videos how powerful dictionary data structure is.
In this assignment, given a number n, you have to write a program that generates a dictionary
d which contains (i, i*i), where i is from 1 to n (both included).
Then you have to just print this dictionary d.

In [33]:
n = int(input())
dict = {}

for i in range(1, n+1):
    dict[i] = i*i
    
print(dict)



6
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


### Questions 8:

There is a robot that wants to go to the charging point to charge itself.
The robot moves in a 2-D plane from the original point (0,0). The robot can
move toward UP, DOWN, LEFT, and RIGHT with given steps.
The trace of robot movement is shown as the following:
UP 5
DOWN 3
LEFT 3
RIGHT 2

In [34]:

import math
#Init vars
pos=[0,0]
moves={"UP":[0,1],
       "DOWN":[0,-1],
       "LEFT":[-1,0],
       "RIGHT":[1,0]}

#Set inputs
UP = int(input())
DOWN = int(input())
LEFT = int(input())
RIGHT = int(input())
data = ["UP 5",
    "DOWN 3",
    "LEFT 3",
    "RIGHT 2"]

#Move robot on valid moves
for inp in data:
    parts=inp.split()    
    mv=parts[0]
    val=parts[1]
    if mv in moves and val.isnumeric():
        pos[0] = pos[0]+ moves[mv][0]*int(val)
        pos[1] = pos[1]+ moves[mv][1]*int(val)

#get distance     
distance=math.sqrt(pos[0]**2 + pos[1]**2)
print(round(distance), "from [0,0] to",pos)

5
3
3
2
2 from [0,0] to [-1, 2]


### Questions 9:
Create a NumPy array starting from 2 till 50 with a step size of 3.

In [2]:
import numpy as np

arr = np.arange(2, 50, 3)

print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


### Questions 10:
Accept two lists of 5 elements each from the user.
Convert them to NumPy arrays. Concatenate these arrays and print them. Also, sort these arrays
and print them.

In [41]:
list1, list2 = [], []

print('LIST 1')
for i in range(5):
    i = int(input())
    list1.append(i)

print('LIST 2')
for j in range(5):
    j = int(input())
    list2.append(j)
    
print(list1)
print(list2)

LIST 1
12
32
45
67
89
LIST 2
12
34
56
87
90
[12, 32, 45, 67, 89] 
 [12, 34, 56, 87, 90]


In [44]:
# array conversion

list1 = np.array(list1)
list2 = np.array(list2)

In [54]:
# concatenated array

concat_arr = np.concatenate((list1, list2), axis=0)

print(concat_arr)

[12 32 45 67 89 12 34 56 87 90]


In [57]:
# sorted array

sort_arr = np.sort(concat_arr)

print(sort_arr)

[12 12 32 34 45 56 67 87 89 90]


### Questions 11:
Write a code snippet to find the dimensions of a ndarray and its size.

In [3]:
arr = np.arange(12).reshape(4,3)

print(arr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [5]:
arr.ndim

2

In [8]:
arr.size

12

### Questions 12:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [16]:
arr = np.arange(9)

arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
arr1 = arr[np.newaxis,:] # new axis

In [18]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
arr2 = np.expand_dims(arr, axis = 1)

arr2

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Questions 13:
Consider two square NumPy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [20]:
arr1 = np.arange(9)

arr2 = np.arange(9,18)

print(arr1)
print(arr2)

[0 1 2 3 4 5 6 7 8]
[ 9 10 11 12 13 14 15 16 17]


In [22]:
np.hstack((arr1,arr2)) # stacking horizontally

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [23]:
np.vstack((arr1,arr2)) # stacking vertically

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

### Questions 14:
How to get unique items and counts of unique items?

In [24]:
arr=np.array([10,20,10,35,55,20,35,90,10,55])
print(arr)
np.unique(arr)
print()
np.unique(arr,return_counts=True)

[10 20 10 35 55 20 35 90 10 55]



(array([10, 20, 35, 55, 90]), array([3, 2, 2, 2, 1], dtype=int64))